Developement environment setup added
oneops/oneops.github.io pull request #20
Opened 2016-12-02 00:25 UTC by shanmukht

Taken care of below guidelines.

https://github.com/oneops/oneops.github.io/issues/7
https://github.com/oneops/oneops.github.io/pull/6

2016-12-02 16:44 UTC, mosabua commented
Thanks for the contribution @shanmukht . I will review later today.

2016-12-02 23:09 UTC, mosabua commented
Documentation guidelines are now at http://oneops.com/developer/contribution/doc-guideline.html fyi @shanmukht

2016-12-02 23:18 UTC, mosabua commented
Somehow have to clarify where these docs are supposed to work in terms of OS. From what I gather these are specific to OSX. Is there any expectation this works with Linux or Windows? It should probably work with Linux imho.

2016-12-02 23:31 UTC, mosabua requested changes
Also... do you want me to test this?

2016-12-02 23:31 UTC, mosabua commented on _includes/dev-navigation.html
> +                  <a href="/developer/environment-setup/index.html">Development Environment Setup</a>
Remove this and move the document itself into /developer/howto

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +id: "environment-setup"
Remove the id. Rename file and move to developer/howto

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +# Pre requisites
Prerequisites is one word.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +1. Java
Use an unordered list with * or -.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +7. Create an **install** directory inside your home directory ($ mkdir ~/install)
Here you are starting with steps... so new list with order maybe.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +    <p align="center">
Replace this image with actual links to the git repositories instead.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +2. Do `mvn clean install` in this specific order : **cmsdal, oo-common, amq-plugin, adapter, antenna, cms-admin, controller, opamp, sensor, transistor, transmitter, inductor**
Is there no aggregator pom for this?

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +    export M2_HOME=~/install/apache-maven-3.3.3
Usage of M2_HOME is no longer recommended for Maven.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +    ```
Why is this list in a code snippet?

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +7. Copy `amqplugin-1.0.0-fat.jar` to ActiveMQ's lib folder (We can find this at manven repository).
Fix spelling and add link to JAR file.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +## Inductor Setup
Should this be  a separate page .. its rather long at this stage.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +        max_consumers = 10
Preferably use code snippet syntax instead of indention.

2016-12-02 23:31 UTC, mosabua commented on developer/environment-setup/index.md
> +2. Install gems
Install bundler

2016-12-05 20:12 UTC, shanmukht commented on developer/environment-setup/index.md
> +id: "environment-setup"
will move this to howto navigation. But want to keep the id with proper name (just to make consistent with other pages).

2016-12-05 21:03 UTC, mosabua commented on developer/environment-setup/index.md
> +id: "environment-setup"
The id is not used for anything. Please remove it

2016-12-05 22:29 UTC, shanmukht commented on developer/environment-setup/index.md
> +2. Do `mvn clean install` in this specific order : **cmsdal, oo-common, amq-plugin, adapter, antenna, cms-admin, controller, opamp, sensor, transistor, transmitter, inductor**
No for this.

2016-12-05 23:57 UTC, shanmukht commented
@mosabua Updated as per review comments.

2016-12-07 16:59 UTC, mosabua commented
lgtm now.. I will merge and do final cosmetic fixes and then push.

2016-12-07 17:16 UTC, mosabua commented
I am fixing this up now locally. There are a LOT of rendering issue. Next time please test the appearance of the article as part of submitting a PR.

2016-12-07 20:04 UTC, merged

2016-12-07 20:35 UTC, mosabua commented
This is now published at http://oneops.com/developer/howto/development-environment-setup.html